[profile.default]
src = "src"
out = "out"
libs = ["lib"]  # Doit être une liste (entre crochets)

remappings = [
    "@openzeppelin=lib/openzeppelin-contracts"
]

solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
holesky = "https://holesky.infura.io/v3/${env:infura}"